### PR TITLE
FIX check products only for extra eu deliveries

### PR DESCRIPTION
**Pull request by bealdav**
ping @alexis-via

### CODE REVIEW

**Comment by alexis-via** [comment]
Now deployed in production at the Barroux abbey

**Comment by bealdav** [comment]
We should choose a more significant branch name for production, isn't it ?
... and delete others.

**Review by alexis-via — CHANGES_REQUESTED** [review]
_should_i_include_customs() should also be used here I guess

**Comment by alexis-via** [comment]
I mean in delivery_roulier_coliposte/stock.py line 190 before "raise orm.except_orm(                u"Déclaration d'échange de bien",
u"Les propriétés DEB/DES (onglet Compta) du produit '%s' "
u"ne sont pas correctement remplis."

**Pull request closed without merging**
