### PR TITLE
Configure the renaming of files .tmp to .ok after their export

### PR DESCRIPTION
**Pull request by guewen**
- [x] needs akretion/file-exchange#2

### CODE REVIEW

**Comment by bealdav** [comment]
:+1:

**Comment by mdietrichc2c** [comment]
:+1:

**Comment by vrenaville** [comment]
:+1:

**Comment by bealdav** [comment]
FYI, new version of coliposte target September with @hparfr. I suppose this code will not be kept, because it becomes full web service.

**Pull request merged**
